# Generated by Django 5.2.13 on 2026-08-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_login_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='name',
            new_name='username',
        ),
    ]
