# Generated by Django 5.2.13 on 2026-09-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_rename_name_login_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('category', models.CharField(max_length=122)),
                ('semester', models.CharField(max_length=122)),
                ('condition', models.CharField(max_length=122)),
                ('price', models.FloatField()),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='shop/images')),
            ],
        ),
    ]
